apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-backend
  template:
    metadata:
      labels:
        app: ecom-backend
    spec:
      containers:
      - name: backend
        image: isaackavetec/api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "your-database-url"
