version: '5'
services:
  web:
    build: ./web
    image: ijeawele/web:latest2
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build: ./api
    image: ijeawele/api:latest2
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: mysql:latest2
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
