apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecom-frontend
  labels:
    app: ecom-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecom-frontend
  template:
    metadata:
      labels:
        app: ecom-frontend
    spec:
      containers:
      - name: frontend
        image: isaackavetec/web:latest
        ports:
        - containerPort: 80
        env:
        - name: API_URL
          value: "http://ecom-backend.default.svc.cluster.local:5000" # Backend Service DNS
